---
project_id: monitoring-project-123
service: service1
slo_id: month-error-rate
display_name: Month | Error rate
goal: 0.999
calendar_period: MONTH
type: request_based_sli
method: good_total_ratio
bad_service_filter: >
  metric.type="knative.dev/serving/revision/request_count"
  resource.type="knative_revision"
  metric.labels.response_code_class="5xx"
  resource.labels.service_name="my-service"
total_service_filter: >
    metric.type="knative.dev/serving/revision/request_count"
    resource.type="knative_revision"
    resource.labels.service_name="my-service"
