---
project_id: monitoring-project-123
service: service1
slo_id: month-availability
display_name: Month | Availability
goal: 0.998
calendar_period: MONTH
type: windows_based_sli
method: boolean_filter
window_period: 60s
metric_filter: >
  metric.type="monitoring.googleapis.com/uptime_check/check_passed"
  resource.type="uptime_url"
  metric.labels.check_id="my-service"
