---
project_id: monitoring-project-123
service: service1
slo_id: month-latency
display_name: Month | Latency
goal: 0.95
calendar_period: MONTH
type: request_based_sli
method: distribution_cut
metric_filter: >
  metric.type="knative.dev/serving/revision/request_latencies"
  resource.type="knative_revision"
  resource.labels.service_name="my-service"
range_min: 0
range_max: 100