{
   "displayName":"Memorystore - ${clan_name} [tf]",
   "gridLayout":{
      "columns":"2",
      "widgets":[
         {
            "title":"Memory Usage Ratio",
            "xyChart":{
               "dataSets":[
                  {
                     "timeSeriesQuery":{
                        "timeSeriesFilter":{
                           "filter": "metric.type=\"redis.googleapis.com/stats/memory/usage_ratio\" resource.type=\"redis_instance\" resource.label.\"project_id\"=\"${clan_project_id}\"",
                           "aggregation":{
                              "perSeriesAligner":"ALIGN_MEAN",
                              "crossSeriesReducer":"REDUCE_MEAN",
                              "groupByFields":[
                                 "resource.label.\"instance_id\""
                              ]
                           }
                        },
                        "unitOverride":"1"
                     },
                     "plotType":"LINE",
                     "targetAxis":"Y1"
                  }
               ],
               "timeshiftDuration":"0s",
               "yAxis":{
                  "label":"y1Axis",
                  "scale":"LINEAR"
               }
            }
         },
         {
            "title":"Used memory",
            "xyChart":{
               "dataSets":[
                  {
                     "timeSeriesQuery":{
                        "timeSeriesFilter":{
                           "filter": "metric.type=\"redis.googleapis.com/stats/memory/usage\" resource.type=\"redis_instance\" resource.label.\"project_id\"=\"${clan_project_id}\"",
                           "aggregation":{
                              "perSeriesAligner":"ALIGN_MEAN",
                              "crossSeriesReducer":"REDUCE_SUM",
                              "groupByFields":[
                                 "resource.label.\"instance_id\""
                              ]
                           }
                        },
                        "unitOverride":"By"
                     },
                     "plotType":"LINE",
                     "targetAxis":"Y1",
                     "minAlignmentPeriod":"60s"
                  }
               ],
               "chartOptions":{
                  "mode":"COLOR"
               },
               "timeshiftDuration":"0s",
               "yAxis":{
                  "label":"y1Axis",
                  "scale":"LINEAR"
               }
            }
         }
      ]
   }
}
