{
   "displayName":"Pub/Sub - ${clan_name} [tf]",
   "gridLayout":{
      "columns":"2",
      "widgets":[
         {
            "title":"Unacked messages",
            "xyChart":{
               "dataSets":[
                  {
                     "timeSeriesQuery":{
                        "timeSeriesFilter":{
                           "filter":"metric.type=\"pubsub.googleapis.com/subscription/num_undelivered_messages\" resource.type=\"pubsub_subscription\" resource.label.\"project_id\"=\"${clan_project_id}\"",
                           "aggregation":{
                              "perSeriesAligner":"ALIGN_COUNT",
                              "crossSeriesReducer":"REDUCE_MEAN",
                              "groupByFields":[
                                 "metadata.system_labels.\"name\""
                              ]
                           }
                        },
                        "unitOverride":"1"
                     },
                     "plotType":"LINE"
                  }
               ],
               "timeshiftDuration":"0s",
               "thresholds":[
                  {
                     "label":"count",
                     "value":1
                  }
               ],
               "thresholds":[
                  {
                     "label":"count",
                     "value":1
                  }
               ],
               "yAxis":{
                  "label":"y1Axis",
                  "scale":"LINEAR"
               }
            }
         },
         {
            "title":"Oldest unacked message age",
            "xyChart":{
               "dataSets":[
                  {
                     "timeSeriesQuery":{
                        "timeSeriesFilter":{
                           "filter":"metric.type=\"pubsub.googleapis.com/subscription/oldest_unacked_message_age\" resource.type=\"pubsub_subscription\" resource.label.\"project_id\"=\"${clan_project_id}\"",
                           "aggregation":{
                              "perSeriesAligner":"ALIGN_MEAN",
                              "crossSeriesReducer":"REDUCE_SUM",
                              "groupByFields":[
                                 "metadata.system_labels.\"name\""
                              ]
                           }
                        },
                        "unitOverride":"s"
                     },
                     "plotType":"LINE",
                     "minAlignmentPeriod":"60s"
                  }
               ],
               "chartOptions":{
                  "mode":"COLOR"
               },
               "timeshiftDuration":"0s",
               "yAxis":{
                  "label":"y1Axis",
                  "scale":"LINEAR"
               }
            }
         },
         {
            "title":"Backlog size[SUM]",
            "xyChart":{
               "dataSets":[
                  {
                     "timeSeriesQuery":{
                        "timeSeriesFilter":{
                           "filter":"metric.type=\"pubsub.googleapis.com/subscription/backlog_bytes\" resource.type=\"pubsub_subscription\" resource.label.\"project_id\"=\"${clan_project_id}\"",
                           "aggregation":{
                              "perSeriesAligner":"ALIGN_MEAN",
                              "crossSeriesReducer":"REDUCE_SUM",
                              "groupByFields":[
                                 "metadata.system_labels.\"name\""
                              ]
                           }
                        },
                        "unitOverride":"By"
                     },
                     "plotType":"LINE",
                     "minAlignmentPeriod":"60s"
                  }
               ],
               "chartOptions":{
                  "mode":"COLOR"
               },
               "timeshiftDuration":"0s",
               "yAxis":{
                  "label":"y1Axis",
                  "scale":"LINEAR"
               }
            }
         },
         {
            "title":"Dead letter message count",
            "xyChart":{
               "dataSets":[
                  {
                     "timeSeriesQuery":{
                        "timeSeriesFilter":{
                           "filter":"metric.type=\"pubsub.googleapis.com/subscription/dead_letter_message_count\" resource.type=\"pubsub_subscription\" resource.label.\"project_id\"=\"${clan_project_id}\"",
                           "aggregation":{
                              "perSeriesAligner":"ALIGN_COUNT",
                              "crossSeriesReducer":"REDUCE_MEAN",
                              "groupByFields":[
                                 "metric.label.\"response_code\"",
                                 "metadata.system_labels.\"subscription_id\""
                              ]
                           }
                        },
                        "unitOverride":"1"
                     },
                     "plotType":"STACKED_BAR",
                     "minAlignmentPeriod":"60s"
                  }
               ],
               "chartOptions":{
                  "mode":"COLOR"
               },
               "timeshiftDuration":"0s",
               "yAxis":{
                  "label":"y1Axis",
                  "scale":"LINEAR"
               }
            }
         },
         {
            "title":"Publish message operation",
            "xyChart":{
               "dataSets":[
                  {
                     "timeSeriesQuery":{
                        "timeSeriesFilter":{
                           "filter":"metric.type=\"pubsub.googleapis.com/topic/send_message_operation_count\" resource.type=\"pubsub_topic\" resource.label.\"project_id\"=\"${clan_project_id}\"",
                           "aggregation":{
                              "perSeriesAligner":"ALIGN_COUNT",
                              "crossSeriesReducer":"REDUCE_MEAN",
                              "groupByFields":[
                                 "metric.label.\"response_code\"",
                                 "metadata.system_labels.\"subscription_id\""
                              ]
                           }
                        },
                        "unitOverride":"1"
                     },
                     "plotType":"STACKED_BAR",
                     "minAlignmentPeriod":"60s"
                  }
               ],
               "chartOptions":{
                  "mode":"COLOR"
               },
               "timeshiftDuration":"0s",
               "yAxis":{
                  "label":"y1Axis",
                  "scale":"LINEAR"
               }
            }
         }
      ]
   }
}
